spring:
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpashop #멀티버전 동시성 컨트롤
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:

        format_sql: true
#        show_sql: true
        use_sql_comments: true

logging:
  level:
    sql: debug
    org.hibernate.type: trace
